class CustomError(Exception):
    pass


class DBError(CustomError):
    pass
